### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by haoyu-x** [HaozhiQi/hora#1]
hi dear authors,

thanks for bringing such great work!

A quick question:  seems that the dependency requirements txt is missing in the document?

Best,
Haoyu

**Comment by HaozhiQi** [comment]
Thanks @haoyu-x. I just made a fix https://github.com/HaozhiQi/hora/commit/cb5b6e5f3ca450d9689f23f07824c030536ee984. It should work now.

**Comment by haoyu-x** [comment]
great! thank you again for open-sourcing hora!
